### ISSUE TITLE
[QUESTION] - OnDestroyView

### ISSUE THREAD

**Issue by jzeferino** [molinch/FFImageLoading#163]
I noticed that in your Android examples you override the `OnDestroyView`.
It is mandatory to use your library?
I'm currently using Picasso, and i consider changing to `FFImageLoading`.
Can you detail that please?

```
public override void OnDestroyView()
		{
			if (_imgDisplay != null)
			{
				_imgDisplay.Dispose();
				_imgDisplay = null;
			}

			base.OnDestroyView();
		}
```

**Comment by molinch** [comment]
@jzeferino It is not mandatory

**Comment by jzeferino** [comment]
Ok, thank you. Any special reason to do that in that example?

**Comment by molinch** [comment]
@c1rus Is there any reason you wrote it? I know it was a while back so maybe you don't remember :)

**Comment by c1rus** [comment]
@molinch hmmm, i think you wrote it. :)

look at this:
https://github.com/molinch/FFImageLoading/commit/6f51cb63e93bbaf59b28c7a35e613355d6e89e17

**Comment by molinch** [comment]
Oh yes my bad! You're totally right :)
Know I remember everything !

Basically @jzeferino when you use FindViewById it is a good practice to dispose views you found (this reduces GC's work).
Which is why I added this call in OnDestroyView.

If you google 'Xamarin FindViewById Dispose' I am sure you will find plenty of interesting resources from StackOverflow or forums.

**Comment by jzeferino** [comment]
Thank you.
