### ISSUE TITLE
How to load image from url on internet

### ISSUE THREAD

**Issue by Englbach** [molinch/FFImageLoading#183]
Xamarin android
if (track.artwork_url != null) {
					viewHolder.Image=FFImageLoading.Views.ImageViewAsync(track.artwork_url);

It don't run.

**Comment by daniel-luberda** [comment]
https://github.com/molinch/FFImageLoading/wiki/Fluent-Syntax

```C#
ImageService.LoadUrl("http://www.funchap.com/wp-content/uploads/2014/05/help-dog-picture.jpg")
.LoadingPlaceholder("loading.png")
.ErrorPlaceholder("error.png")
.Retry(3, 200)
.Into(_imageView);
```

**Comment by Englbach** [comment]
Error CS1928: Type `FFImageLoading.Work.TaskParameter' does not contain a member `Into' and the best extension method overload `FFImageLoading.TaskParameterExtensions.Into(this FFImageLoading.Work.TaskParameter, FFImageLoading.Views.ImageViewAsync)' has some invalid arguments (CS1928) 

viewHolder.Image = view.FindViewById<ImageView> (Resource.Id.image);
ImageService.LoadUrl(track.artwork_url)
						.LoadingPlaceholder("loading.png")
						.ErrorPlaceholder("error.png")
						.Retry(3, 200)
						.Into(viewHolder.Image);
public class TrackViewHolder:Java.Lang.Object
		{
			public TextView Title{ get; set;}
			public TextView SubTitle{get;set;}
			public ImageView Image{ get; set;}
			public ImageView ImgIcon{get;set;}
			public TextView PlayingCount{get;set;}
		}

**Comment by daniel-luberda** [comment]
There's whole Android example in Samples: https://github.com/molinch/FFImageLoading/blob/master/samples/ImageLoading.Sample/ImageFragment.cs

**Comment by mr5z** [comment]
Does `.Into` available in cross platform also?

**Comment by tdbe** [comment]
> 
> 
> https://github.com/molinch/FFImageLoading/wiki/Fluent-Syntax
> 
> ```cs
> ImageService.LoadUrl("http://www.funchap.com/wp-content/uploads/2014/05/help-dog-picture.jpg")
> .LoadingPlaceholder("loading.png")
> .ErrorPlaceholder("error.png")
> .Retry(3, 200)
> .Into(_imageView);
> ```

What does the XAML look like? What is `_imageView` in XAML?
I feel that this example needs to be the first thing in this repo's Readme.md.
All examples on the internet for FFImage are about setting up a static image in xaml that loads everything itself on start. I just want to load a custom url at runtime programmatically from c#...

The wiki (which btw has poor SEO since it never shows in google results on any of these issues) never mentions how to make a XAML FFImage with a x:Name="myFFImage" that I can reference from C#. Why?? How do thing FFS?

------ 

Here's my trial and error answer:

```
<ffimageloading:CachedImage x:Name="myImage" 
Margin="0,0,0,0" WidthRequest="300" HeightRequest="300"
Grid.Row="0" Grid.Column="0"
></ffimageloading:CachedImage>
```

^ note the absence of a Source attribute. This is probably wrong, but I want the image to load -nothing- and show -nothing- until I do it programmatically from c#.

Then in c#:
```
        public class FFImageLoaderSettings
        {
            public TimeSpan CacheDuration = TimeSpan.FromDays(7);
            public bool DownsampleToViewSize = true;
            public int RetryCount = 5;
            public int RetryDelay = 1000;
            public bool BitmapOptimizations = false;
            public string LoadingPlaceholder = "loading.png";
            public string ErrorPlaceholder = "error.png";
            public string SourceBase = "https://www.mywebsite.com/images/";
            
        }
        public FFImageLoaderSettings globalFFImageLoaderSettings;

        public FFImageLoading.Forms.CachedImage GetFFImageFromWeb(FFImageLoading.Forms.CachedImage xamlFFimage, string imageName)
        {
            FFImageLoading.Forms.CachedImage cachedImage = new FFImageLoading.Forms.CachedImage()
            {
                HorizontalOptions = LayoutOptions.Center,
                VerticalOptions = LayoutOptions.Center,
                WidthRequest = xamlFFimage.WidthRequest,
                HeightRequest = xamlFFimage.HeightRequest,
                CacheDuration = AppLoader._Instance.globalFFImageLoaderSettings.CacheDuration,
                DownsampleToViewSize = AppLoader._Instance.globalFFImageLoaderSettings.DownsampleToViewSize,
                RetryCount = AppLoader._Instance.globalFFImageLoaderSettings.RetryCount,
                RetryDelay = AppLoader._Instance.globalFFImageLoaderSettings.RetryDelay,
                BitmapOptimizations = AppLoader._Instance.globalFFImageLoaderSettings.BitmapOptimizations,
                //LoadingPlaceholder = AppLoader._Instance.globalFFImageLoaderSettings.LoadingPlaceholder,
                //ErrorPlaceholder = AppLoader._Instance.globalFFImageLoaderSettings.ErrorPlaceholder, 
                Source = AppLoader._Instance.globalFFImageLoaderSettings.SourceBase + imageName
            };
            return cachedImage;
        }
        // ^ I do NOT want placeholders or error images (I have my own multi-vector object loader illustrations / animations); 
        // I want FFImage to do 0 processing until I just request an image.

        // ... then when you want an image:
        myImage = AppLoader._Instance.GetFFImageFromWeb(myImage, "targetIMage.jpg"); 

```

Now the question is does this code use caching at all? When I request an image, will it internally check if that image already exists and it is within the 7 day cache period and then not re-download it? I hope so, but I guess I better experiment to find out..


PS: The Events section says NOTHING: https://github.com/luberda-molinet/FFImageLoading/wiki/Xamarin.Forms-API
How do I subscribe to an event?? How do basic thing?
