### ISSUE TITLE
Into does not exist

### ISSUE THREAD

**Issue by nvasilescu** [molinch/FFImageLoading#21]
ImageService.LoadUrl (imagePath).Into (mainImageView);

FFImageLoading.Work.TaskParameter does not contain a definition for Into ....

**Comment by molinch** [comment]
Hi,

This is an extension method.
You need to import the namespace.

**Comment by nvasilescu** [comment]
it is imported . 

using FFImageLoading;

![s1](https://cloud.githubusercontent.com/assets/4938117/8043779/e7fdf7fc-0e30-11e5-9dc8-f925cd4c711b.jpg)

**Comment by molinch** [comment]
Currently, on Android, FFImageLoading only supports loading images into FFImageLoading.Views.ImageViewAsync. It is a subclass of ImageView. This limitation might change in the future.

Documentation shows it:
<pre>
Note on Android: Unlike Picasso you cannot use FFImageLoading with standard ImageViews. Instead simply load your images into ImageViewAsync instances. Updating your code is very easy since ImageViewAsync inherits from ImageView.
</pre>

**Comment by gustaveracosta** [comment]
I am having the same issue for iOS, the documentation still showing to use this form. They must have changed the API and forgot to update the documentation
