### ISSUE TITLE
Feature request: load to Bitmap instead of ImageViewAsync

### ISSUE THREAD

**Issue by softwaremills** [molinch/FFImageLoading#59]
FFImageLoading is pretty fantastic. I have a use case where I'm making Android notifications that require `Bitmap`s. Could you make an overload of `Into` that loads into `Bitmap`s or something similar instead of `ImageViewAsync`s?

I did try making a `SideEffectTransformation` that would copy the bitmap in directly, but immediately worried that caching would prevent future notifications with the same image from displaying properly.

And I tried loading into an ImageViewAsync and doing `Draw` to draw into a bitmap, but the resulting bitmap was transparent even with `FadeAnimation(false)`.

Thanks for all your hard work!

**Comment by molinch** [comment]
Thanks @softwaremills!

Your need is really a special use case, that would not fit into this lib, therefore it should not be that hard to implement it on your side. You could subclass ImageLoaderTask and totally bypass the WorkScheduler.

Your subclass could have a method `RetrieveBitmapAsync`:
```cs
public async Task<Bitmap> RetrieveBitmapAsync()
{
	// Try to load from cache first
	var key = GetKey();
	if (!string.IsNullOrWhiteSpace(key))
	{
		var cachedDrawable = ImageCache.Instance.Get(key);
		if (cachedDrawable != null)
			return cachedDrawable.GetBitmap();
	}

	// Otherwise load image normally
	var drawableWithResult = await GetDrawableAsync(Parameters.Path, Parameters.Source, false).ConfigureAwait(false);
	if (drawableWithResult == null || drawableWithResult.Item == null)
		return null;

	// If we have the bitmap we add it to the cache
	ImageCache.Instance.Add(GetKey(sourcePath), drawableWithResult.Item);

	return drawableWithResult.Item.GetBitmap();
}
```

Then if you have your own version of it, you can instantiate it and await it:
```cs
var parameters = ImageService.LoadUrl(urlToImage); // just change this to fit your needs
var task = new MyImageLoaderTaskSubclass(ImageService.Config.DownloadCache, new MainThreadDispatcher(), ImageService.Config.Logger, parameters, null); 
var bitmap = await task.RetrieveBitmapAsync();
```

**Comment by softwaremills** [comment]
Works great, many thanks!

For posterity, my final class looked like this:

	public class BitmapLoaderTask : ImageLoaderTask {
		public BitmapLoaderTask(string url)
			: base(ImageService.Config.DownloadCache, new MainThreadDispatcher(), ImageService.Config.Logger,
				ImageService.LoadUrl(url).TransparencyChannel(true), null)
		{
		}

		public async Task<Bitmap> RetrieveBitmapAsync()
		{
			// Try to load from cache first
			var key = GetKey();
			if (!string.IsNullOrWhiteSpace(key))
			{
				var cachedDrawable = ImageCache.Instance.Get(key);
				if (cachedDrawable != null)
					return cachedDrawable.Bitmap;
			}

			// Otherwise load image normally
			var drawableWithResult = await GetDrawableAsync(Parameters.Path, Parameters.Source, false).ConfigureAwait(false);
			if (drawableWithResult == null || drawableWithResult.Item == null)
				return null;

			// If we have the bitmap we add it to the cache
			ImageCache.Instance.Add(GetKey(), drawableWithResult.Item);

			return drawableWithResult.Item.Bitmap;
		}
	}

**Comment by molinch** [comment]
Thanks for the feedback!

**Comment by Finneyv** [comment]
Hey I am running into the same problem brought up by this question.  But I have found that the syntax with inheriting and calling ImageTaskLoader has changed a lot over the last two years.  I was wondering if there is an example or documentation of how one would inherit the current ImageLoaderTask to do this.

**Comment by softwaremills** [comment]
Yeah, I think there's an officially-sanctioned version of how to do it these days. Later versions of our product didn't need this functionality, so I'm not sure of the details.

**Comment by daniel-luberda** [comment]
Currently, you should use:

- `await ImageService.Instance.LoadFile(xxx).DownSample(width: xxx).AsBitmapDrawableAsync()` for Android
- `await ImageService.Instance.LoadFile(xxx).DownSample(width: xxx).AsUIImageAsync()` for iOS
- `await ImageService.Instance.LoadFile(xxx).DownSample(width: xxx).AsBitmapDrawableAsync()` for Windows (yeah I noticed bad naming, we should change it in future)

**Comment by Finneyv** [comment]
Hey thanks for your reply and sorry for not getting back to you in a while. I'm trying to implement your solution but for some reason the code never completes.  I just get a system aggregate exception due to the task timing out.  Do you know why that might be?

**Comment by daniel-luberda** [comment]
@Finneyv  Is your image from url source?

**Comment by Finneyv** [comment]
Yes it is. It's a jpg.

**Comment by daniel-luberda** [comment]
Then it must be some connection issue, please attach stack trace.

**Comment by Finneyv** [comment]
Here is an example of the stack trace:
Xamarin caused by: android.runtime.JavaProxyThrowable: System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.TypeLoadException: Could not resolve type with token 0100013c (from typeref, class/assembly FFImageLoading.TaskParameterPlatformExtensions, FFImageLoading.Platform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].Start[TStateMachine] (TStateMachine& stateMachine) [0x0002c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
  at DABApp.Droid.AudioService.fetchBitmap (System.String imageUri) [0x00023] in <e2a16aeec5884a15b39e12b79950e58c>:0 
  at DABApp.Droid.AudioService+<>c__DisplayClass29_0+<<SetMetaData>b__2>d.MoveNext () [0x0004a] in <e2a16aeec5884a15b39e12b79950e58c>:0 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.TypeLoadException: Could not resolve type with token 0100013c (from typeref, class/assembly FFImageLoading.TaskParameterPlatformExtensions, FFImageLoading.Platform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
  at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[TResult].Start[TStateMachine] (TStateMachine& stateMachine) [0x0002c] in <896ad1d315ca4ba7b117efb8dacaedcf>:0 
  at DABApp.Droid.AudioService.fetchBitmap (System.String imageUri) [0x00023] in <e2a16aeec5884a15b39e12b79950e58c>:0 
  at DABApp.Droid.AudioService+<>c__DisplayClass29_0+<<SetMetaData>b__2>d.MoveNext () [0x0004a] in <e2a16aeec5884a15b39e12b79950e58c>:0 <---

And here is the fetchBitmap method:

`async Task<Android.Graphics.Bitmap> fetchBitmap(string imageUri)
		{
			try
			{
				var draw = await ImageService.Instance.LoadUrl(imageUri).DownSample().AsBitmapDrawableAsync();
				return draw.Bitmap;
			}
			catch (Exception e)
			{
				Debug.WriteLine($"Bitmap exception: {e.Message}");
				return null;
			}
		}`

**Comment by daniel-luberda** [comment]
You have mixed different FFImageLoading versions in your projects, also
remove all bin / obj folders

**Comment by Finneyv** [comment]
Thanks!  That seemed to do the trick.
